branches:
  only:
    - /^v[0-9]+(\.[0-9]+){2}$/
dist: trusty
language: node_js
node_js:
  - 8
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/api-espm:$TRAVIS_TAG
script: 
  - scripts/travis.sh
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh api api api-espm
  on:
    tags: true
